import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import worker, { authenticate, validAmount } from '../server/worker.mjs';
const token = 'test-token-not-a-real-secret';
const now = Date.now();
const params = new URLSearchParams({auth_date:String(Math.floor(now/1000)),user:JSON.stringify({id:12345}),query_id:'test-query'});
const data = [...params.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');
const key = createHmac('sha256','WebAppData').update(token).digest();
params.set('hash',createHmac('sha256',key).update(data).digest('hex'));
assert.equal(await authenticate(params.toString(),token,now),12345);
await assert.rejects(authenticate(params.toString().replace('12345','99999'),token,now));
await assert.rejects(authenticate(params.toString(),token,now+3601000));
await assert.rejects(authenticate(params.toString()+'&user=%7B%22id%22%3A5%7D',token,now));
for (const amount of [5,6,99,100,1000,10000,999999]) assert.ok(validAmount(amount));
for (const amount of [0,-1,1000000,1000001,5.5,'10',Infinity]) assert.ok(!validAmount(amount));
const env = {APP_ORIGIN:'https://tunetotslab.github.io',BOT_TOKEN:token,WEBHOOK_SECRET:'test-only'};
assert.equal((await worker.fetch(new Request('https://example.com/donations',{method:'POST',headers:{Origin:env.APP_ORIGIN},body:'{}'}),env)).status,401);
assert.equal((await worker.fetch(new Request('https://example.com/telegram/webhook',{method:'POST',body:'{}'}),env)).status,403);
assert.equal((await worker.fetch(new Request('https://example.com/donations',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),env)).status,403);
console.log('PASS signed Telegram auth, tampering, expiry, duplicate keys, donation amounts, unauthorized routes and webhook');
